name: Build to GCR

on:
  workflow_dispatch:
  
  # push:
  #   branches: [main]

env:
  PRODUCT_NAME: "nautical-analytics"
  PRODUCT_VERSION: ${{ github.run_number}}  # Set your version here

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    permissions:    
      id-token: write
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEMO_GH_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nautical-analytics:latest
            ghcr.io/${{ github.repository_owner }}/nautical-analytics:${{ env.PRODUCT_VERSION }}

      - name: Create and Upload Image SBOM
        uses: scribe-security/action-bom@master
        env:
            SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          target: "ghcr.io/${{ github.repository_owner }}/nautical-analytics:${{ env.PRODUCT_VERSION }}"
          base-image: Dockerfile
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          # components: files
          format: attest

      - name: Create and Upload Git SBOM
        uses: scribe-security/action-bom@master
        env:
            SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          target: 'git:.'
          # asset-type: repo
          # asset-id: ${{ github.repository }}
          # asset-name: ${{ env.REPO_BASE_NAME}}
          # asset-platform: github
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          # components: files
          format: attest

      - name: Create and verify SLSA
        uses: scribe-security/action-verify@master
        env:
            SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
        with:
          target: "ghcr.io/${{ github.repository_owner }}/nautical-analytics:${{ env.PRODUCT_VERSION }}"
          provenance: true
          product-key: ${{ env.PRODUCT_NAME }}
          product-version: ${{ env.PRODUCT_VERSION }}
          # components: files
          format: attest
          initiative: slsa.l2@v2
          beautify: true

      # - name: verify-ssdf
      #   if: always()
      #   uses: scribe-security/action-verify@master
      #   env: 
      #       SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
      #   with:
      #     target: "ghcr.io/${{ github.repository_owner }}/nautical-analytics:${{ env.PRODUCT_VERSION }}"
      #     product-key: ${{ env.PRODUCT_NAME }}
      #     product-version: ${{ env.PRODUCT_VERSION }}
      #     base-image: Dockerfile
      #     components: files
      #     format: attest
      #     initiative: ssdf@v2
      #     beautify: true
        
      # - name: verify-sp800-190
      #   uses: scribe-security/action-verify@dev
      #   if: always()
      #   continue-on-error: true # Also makes the step not fail i guessing
      #   env: 
      #       SCRIBE_TOKEN: ${{ secrets.SCRIBE_TOKEN }}
      #   with:
      #     target: "ghcr.io/${{ github.repository_owner }}/nautical-analytics:${{ env.PRODUCT_VERSION }}"
      #     product-key: ${{ env.PRODUCT_NAME }}
      #     product-version: ${{ env.PRODUCT_VERSION }}
      #     base-image: Dockerfile
      #     # input: trivy:trivy-report.json # 2DO Scribe CVE rule to initiative willr replace this requriement.
      #     format: attest
      #     initiative: sp-800-190@v2
      #     beautify: true
      #     # exit-code: 0
